CREATE DATABASE DB_PIZZARIA

USE DB_PIZZARIA

CREATE TABLE TB_CLIENTE
(
	  CD_CLIENTE	INT PRIMARY KEY NOT NULL IDENTITY(1,1)
	, NM_CLIENTE	VARCHAR(255)    NOT NULL
	, NR_TELEFONE	INT             NOT NULL
	, ENDERECO		VARCHAR(255)    NOT NULL
)

INSERT INTO TB_CLIENTE
(
NM_CLIENTE
,NR_TELEFONE
,ENDERECO
)
VALUES
(
'DANIEL'
,32271636
,'RUA CARLOS DE CAMPOS'
)

SELECT * FROM TB_CLIENTE

CREATE TABLE TB_PRODUTO
(
	  CD_PRODUTO	INT PRIMARY KEY NOT NULL IDENTITY(1,1)
	, NM_PRODUTO	VARCHAR(255)    NOT NULL
	, NR_QUANTIDADE INT             NOT NULL
	, VL_PRODUTO	FLOAT           NOT NULL
)

INSERT INTO TB_PRODUTO
(
NM_PRODUTO
,NR_QUANTIDADE
,VL_PRODUTO
)
VALUES
(
'MUSSARELA'
,100
,20
)


CREATE TABLE TB_PEDIDO
(
	  CD_PEDIDO		INT PRIMARY KEY NOT NULL IDENTITY(1,1)
	, DT_PEDIDO 	DATETIME		NOT NULL
	, CD_CLIENTE	INT             NOT NULL
	, VL_TOTAL   	FLOAT           NOT NULL
	, DS_OBSERVACAO VARCHAR(255)    NOT NULL
	, FOREIGN KEY(CD_CLIENTE)
	  REFERENCES TB_CLIENTE(CD_CLIENTE)
)

INSERT INTO TB_Pedido
(
DT_PEDIDO
,CD_CLIENTE
,VL_TOTAL
,DS_OBSERVACAO
)
VALUES
(
'2018-10-10'
,1
,100
,'NADA'
)


CREATE TABLE TB_ITEMPEDIDO
(
	  CD_ITEMPEDIDO	INT PRIMARY KEY NOT NULL IDENTITY(1,1)
	, CD_PRODUTO	INT				NOT NULL
	, CD_PEDIDO		INT				NOT NULL
	, VL_PRODUTO	FLOAT           NOT NULL
	, NR_QUANTIDADE INT				NOT NULL
	, FOREIGN KEY(CD_PRODUTO)
	  REFERENCES TB_PRODUTO(CD_PRODUTO)
	, FOREIGN KEY(CD_PEDIDO)
	  REFERENCES TB_PEDIDO(CD_PEDIDO)
)

SELECT P.CD_PEDIDO, P.DT_PEDIDO, C.NM_CLIENTE, C.NR_TELEFONE, C.ENDERECO FROM TB_PEDIDO P INNER JOIN TB_CLIENTE C ON P.CD_CLIENTE = C.CD_CLIENTE ORDER BY CD_PEDIDO