CREATE TABLE TB_CONTATO
(
  CD_CONTATO  INT          IDENTITY NOT NULL
 ,NM_CONTATO  VARCHAR(255)          NOT NULL
 ,NR_TELEFONE VARCHAR(255)          NOT NULL
 ,NM_EMAIL    VARCHAR(255)          NULL
 ,CONSTRAINT PK_TB_CONTATO PRIMARY KEY(CD_CONTATO)
)

SELECT *
FROM TB_CONTATO